apiVersion: network.azure.crossplane.io/v1alpha3
kind: SecurityGroup
metadata:
  name: roy-cerberus-sg
spec:
  location: eastus
  reclaimPolicy: Delete
  resourceGroupName: cerberus_squad
  providerRef:
    name: azure-provider
  resourceGroupNameRef:
    name: cerberus_squad
  properties:
    securityRules:
      - name: InRule_Protocol
        properties: 
          protocol: 'ICMP'
          sourcePortRange: '*'
          access: Allow
          priority: 130
          direction: Inbound
          destinationPortRange: '*'
          sourceAddressPrefix: '*'
          destinationAddressPrefix: '*'

          
